/**
 * Device-related type definitions for mobile push notification registration.
 * Used by DeviceStore and the mobile API router.
 */

export interface DeviceRecord {
  /** Stable per-install UUID generated by the mobile app and stored in SecureStore */
  deviceId: string;
  /** Owner user ID (from JWT sub) */
  userId: string;
  /** Expo push token string (e.g. ExponentPushToken[...]) */
  expoPushToken: string;
  /** Platform — only iOS is supported in Phase 1 */
  platform: 'ios';
  /** App version string (e.g. "1.0.0") */
  appVersion: string;
  /** ISO-8601 timestamp of first registration */
  registeredAt: string;
  /** ISO-8601 timestamp of last update */
  updatedAt: string;
}
